### ISSUE TITLE
XSS vulns

### ISSUE THREAD

**Issue by bluey2000k** [cheeserox/cheeserox#119]
Comments on watch.php (fixed)

![image](https://user-images.githubusercontent.com/88458384/147864731-f7f9b01a-23db-4f5e-97c7-c504d61cff36.png)
![image](https://user-images.githubusercontent.com/88458384/147864752-23f620f3-48c4-4831-acc9-7e28e2e6ec42.png)

Display names on user.php

![image](https://user-images.githubusercontent.com/88458384/147864742-209b148e-fa57-45c8-88f2-0a2db0fc4e80.png)
![image](https://user-images.githubusercontent.com/88458384/147864745-0a8c23d3-26a7-49f4-8de9-006395ed9385.png)

**Comment by the-real-sumsome** [comment]
lol

**Comment by Hedy88** [comment]
yooo, this is epic. time to self hot DVWA and practice my XSS skills :him:

**Comment by bluey2000k** [comment]
ok so I fixed the XSS for comments but display names XSS seems to be hit or miss.

this will be closed when i will blacklist any unusual symbols for display names

**Comment by bluey2000k** [comment]
apparently comments XSS was due to how the twig template file was made. so it didn’t filter anything whatsoever

**Comment by grkb-chaziz** [comment]
OH MY FUCKING GOD

![image](https://github.com/bluffingo/OpenSB/assets/45898787/03a972ea-7f8e-4bd9-b4ed-23a7f14a73a6)
