### ISSUE TITLE
Project sbNext

### ISSUE THREAD

**Issue by PF94** [cheeserox/cheeserox#40]
sbNext is the codename of the next design of squareBracket
![image](https://user-images.githubusercontent.com/45898787/142685283-421a6f9a-5f44-4e43-83c2-9a55526ff85e.png)

# Design ideas
https://getbootstrap.com/1.4.0/

https://getbootstrap.com/2.3.2/base-css.html

https://getbootstrap.com/2.3.2/components.html

https://web.archive.org/web/20130701010228/https://twitter.com/

https://web.archive.org/web/20130630195051/https://twitter.com/about

https://web.archive.org/web/20120701004652/http://www.youtube.com/ (Epic Panda/Proto-Hitchhiker YouTube)

https://web.archive.org/web/20120630002750/http://www.youtube.com/

https://web.archive.org/web/20120711234416/https://www.youtube.com/user/CaptainSparklez

https://web.archive.org/web/20120818132533/http://www.roblox.com/

https://web.archive.org/web/20130514223939/http://www.roblox.com/

https://web.archive.org/web/20130608035611/http://blog.roblox.com/2013/05/spotlight-aaronstone4real-klammans-klamknights-city/?utm_source=rss&utm_medium=rss&utm_campaign=spotlight-aaronstone4real-klammans-klamknights-city

**Comment by chaziz94** [comment]
![image](https://user-images.githubusercontent.com/45898787/124845672-34797c80-df65-11eb-919a-14b257fdd3fe.png)

added borders to thumbnails, weird spacing issue makes them look a bit like polaroids.

**Comment by chaziz94** [comment]
due to the subrocks/goodtube drama, i believe we should not use any thing from goodtube.

relating to the whole drama, i kind of side with subrocks.

i do remember that the original sbnext css from even before sbnext was worked on isn't complete, but we should use it for sbnext.

**Comment by veselcraft** [comment]
https://user-images.githubusercontent.com/22993408/127293637-ff80b000-1e71-4ef5-8181-b3808b642b02.mp4

**Comment by chaziz94** [comment]
> default.mp4

can you upload this on sb lmao

**Comment by EricZhang456** [comment]
will it do anything else besides being more like 2010 yt

**Comment by chaziz94** [comment]
sbnext doesn't look like 2010 yt

also any elements of a old YouTube clone aren't on squarebracket

**Comment by EricZhang456** [comment]
ok

**Comment by veselcraft** [comment]
ok

**Comment by rollerozxa** [comment]
ok

Sent from my PinePhone

**Comment by chaziz94** [comment]
ok

Sent from the world's gayest Samsung Galaxy A50.

**Comment by veselcraft** [comment]
ok

**Comment by chaziz94** [comment]
sure do love it when people think is sbnext is the future of squarebracket despite the fact that NO ONE is working on it.

it's sitting in the code, and hasen't been touched since pre-beta.

**Comment by chaziz94** [comment]
![image](https://user-images.githubusercontent.com/45898787/139558402-efc39468-a6ca-49e6-93ad-32496ec81104.png)

:trollface:

**Comment by PF94** [comment]
scrapping sbnext in favour of randley layout due to bloat issues and recycled bootstrap code
